export const WHATSAPP_NUMBER = "233554367094";

export const MOCK_CARS = [
  {
    id: "1",
    name: "Mercedes-Benz G-Wagon",
    make: "Mercedes-Benz",
    model: "G-Wagon",
    year: 2022,
    price: 850000,
    mileage: 12000,
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "SUV",
    condition: "Foreign Used",
    sold: false,
    description: "Stunning Mercedes-Benz G-Wagon in pristine condition. This iconic SUV combines luxury with off-road capability, featuring a powerful V8 engine, premium leather interior, and the latest MBUX infotainment system. Imported directly from Europe with full service history.",
    specs: {
      engine: "4.0L V8 Biturbo",
      horsepower: "416 HP",
      torque: "450 lb-ft",
      drivetrain: "AWD",
      seats: 5,
      color: "Obsidian Black",
      interior: "Nappa Leather — Black",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/9e532a19f_generated_c276cafd.png",
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/38f77bb58_generated_781d9f14.png",
    ],
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "2",
    name: "Toyota Camry XSE",
    make: "Toyota",
    model: "Camry",
    year: 2023,
    price: 320000,
    mileage: 5000,
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "Sedan",
    condition: "Brand New",
    sold: false,
    description: "Brand new Toyota Camry XSE with aggressive sport styling. Features include a 2.5L Dynamic Force engine, panoramic moonroof, JBL premium audio, and Toyota Safety Sense 2.5+. Zero accidents, factory warranty intact.",
    specs: {
      engine: "2.5L 4-Cylinder",
      horsepower: "206 HP",
      torque: "186 lb-ft",
      drivetrain: "FWD",
      seats: 5,
      color: "Wind Chill Pearl",
      interior: "Red Leather Sport",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/7a404526e_generated_dfada87f.png",
    ],
    video: null,
  },
  {
    id: "3",
    name: "Honda CR-V Touring",
    make: "Honda",
    model: "CR-V",
    year: 2021,
    price: 280000,
    mileage: 35000,
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "SUV",
    condition: "Foreign Used",
    sold: false,
    description: "Well-maintained Honda CR-V Touring with low mileage. Loaded with Honda Sensing suite, wireless Apple CarPlay, heated leather seats, and power tailgate. Single owner, no accidents, full service records available.",
    specs: {
      engine: "1.5L Turbo 4-Cylinder",
      horsepower: "190 HP",
      torque: "179 lb-ft",
      drivetrain: "AWD",
      seats: 5,
      color: "Lunar Silver Metallic",
      interior: "Leather — Gray",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/ed3f71ded_generated_86b21604.png",
    ],
    video: null,
  },
  {
    id: "4",
    name: "BMW 330i M Sport",
    make: "BMW",
    model: "3 Series",
    year: 2022,
    price: 450000,
    mileage: 18000,
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "Sedan",
    condition: "Foreign Used",
    sold: true,
    description: "BMW 330i with the M Sport package. Features include adaptive M suspension, M Sport brakes, live cockpit professional, and Harman Kardon surround sound. A true driver's car with a turbocharged inline-6.",
    specs: {
      engine: "2.0L Turbo 4-Cylinder",
      horsepower: "255 HP",
      torque: "295 lb-ft",
      drivetrain: "RWD",
      seats: 5,
      color: "Portimao Blue",
      interior: "Vernasca Leather — Black",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/7cf12254d_generated_cbfa5012.png",
    ],
    video: null,
  },
  {
    id: "5",
    name: "Toyota RAV4 XLE",
    make: "Toyota",
    model: "RAV4",
    year: 2023,
    price: 310000,
    mileage: 8000,
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "SUV",
    condition: "Foreign Used",
    sold: false,
    description: "Nearly new Toyota RAV4 XLE with premium features. Includes dual-zone climate control, 8-inch touchscreen, blind spot monitoring, and Toyota Safety Sense 2.0. Perfect for city driving and weekend adventures.",
    specs: {
      engine: "2.5L 4-Cylinder",
      horsepower: "203 HP",
      torque: "184 lb-ft",
      drivetrain: "AWD",
      seats: 5,
      color: "Supersonic Red",
      interior: "Fabric — Black",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/171951325_generated_1ec9a3a3.png",
    ],
    video: null,
  },
  {
    id: "6",
    name: "Mercedes-Benz E300",
    make: "Mercedes-Benz",
    model: "E-Class",
    year: 2021,
    price: 520000,
    mileage: 25000,
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "Sedan",
    condition: "Foreign Used",
    sold: false,
    description: "Executive Mercedes-Benz E300 with AMG Line exterior. Features MBUX with augmented reality navigation, Burmester 3D surround sound, 64-color ambient lighting, and driver assistance package. The pinnacle of executive travel.",
    specs: {
      engine: "2.0L Turbo 4-Cylinder",
      horsepower: "255 HP",
      torque: "273 lb-ft",
      drivetrain: "RWD",
      seats: 5,
      color: "Obsidian Black",
      interior: "Nappa Leather — Macchiato Beige",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/d0a318ebb_generated_2ddb5a36.png",
    ],
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "7",
    name: "Hyundai Tucson SEL",
    make: "Hyundai",
    model: "Tucson",
    year: 2022,
    price: 240000,
    mileage: 15000,
    transmission: "Automatic",
    fuel: "Petrol",
    bodyType: "SUV",
    condition: "Foreign Used",
    sold: false,
    description: "Stylish Hyundai Tucson SEL with a striking design. Features a 10.25-inch digital instrument cluster, 8-inch navigation touchscreen, Hyundai SmartSense, and wireless charging. Excellent fuel economy for a compact SUV.",
    specs: {
      engine: "2.5L 4-Cylinder",
      horsepower: "187 HP",
      torque: "178 lb-ft",
      drivetrain: "FWD",
      seats: 5,
      color: "Cream White",
      interior: "Cloth — Gray",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/171c4e7a5_generated_25a6a620.png",
    ],
    video: null,
  },
  {
    id: "8",
    name: "Toyota Land Cruiser",
    make: "Toyota",
    model: "Land Cruiser",
    year: 2020,
    price: 750000,
    mileage: 42000,
    transmission: "Automatic",
    fuel: "Diesel",
    bodyType: "SUV",
    condition: "Foreign Used",
    sold: true,
    description: "Legendary Toyota Land Cruiser V8 with unmatched off-road prowess. Features Kinetic Dynamic Suspension, multi-terrain select, crawl control, and premium leather interior. Built for Ghana's roads — any road.",
    specs: {
      engine: "4.5L V8 Twin-Turbo Diesel",
      horsepower: "268 HP",
      torque: "479 lb-ft",
      drivetrain: "AWD",
      seats: 7,
      color: "Attitude Black",
      interior: "Semi-Aniline Leather — Black",
    },
    images: [
      "https://media.base44.com/images/public/6a5166ae47e3a25d1b6256a7/9e532a19f_generated_c276cafd.png",
    ],
    video: null,
  },
];

export const MOCK_REVIEWS = [
  {
    id: "1",
    name: "Kwame Asante",
    rating: 5,
    message: "F1 Deals made buying my first car incredibly smooth. The process was transparent from start to finish and the vehicle arrived in better condition than I expected. Highly recommend to anyone in Ghana.",
    date: "2024-11-15",
    approved: true,
  },
  {
    id: "2",
    name: "Ama Serwaa",
    rating: 5,
    message: "I swapped my old Corolla for a newer model through F1 Deals. They handled everything — valuation, paperwork, delivery. Professional service all the way.",
    date: "2024-10-28",
    approved: true,
  },
  {
    id: "3",
    name: "Daniel Mensah",
    rating: 4,
    message: "Got a Honda CR-V shipped from Tema to Kumasi. Communication was excellent and the car was delivered on time. Will definitely use their services again.",
    date: "2024-09-12",
    approved: true,
  },
  {
    id: "4",
    name: "Efua Boateng",
    rating: 5,
    message: "The best car broker in Ghana, period. I've purchased three vehicles through F1 Deals over the past two years and every experience has been top-tier. They negotiate hard and deliver quality.",
    date: "2024-08-05",
    approved: true,
  },
  {
    id: "5",
    name: "Kofi Darko",
    rating: 4,
    message: "Very responsive on WhatsApp and the car was exactly as described. Fair pricing and no hidden fees. F1 Deals is the real deal.",
    date: "2024-07-20",
    approved: true,
  },
];

export const SERVICES = [
  {
    id: "01",
    title: "Car Buying",
    description: "Source your dream vehicle from our curated inventory or let us find exactly what you're looking for. We handle sourcing, inspection, documentation, and delivery nationwide.",
    whatsappMessage: "Hi F1 Deals, I'm interested in buying a car. Can you help me find the right vehicle?",
  },
  {
    id: "02",
    title: "Car Selling",
    description: "Get the best value for your vehicle. We provide fair market valuations, professional photography, and connect you with serious buyers across Ghana.",
    whatsappMessage: "Hi F1 Deals, I'd like to sell my car. Can we discuss the process?",
  },
  {
    id: "03",
    title: "Car Swapping",
    description: "Upgrade or change your vehicle without the hassle. We facilitate seamless trade-ins and swaps, handling all the logistics and paperwork for both parties.",
    whatsappMessage: "Hi F1 Deals, I'm interested in swapping my car. What options do you have?",
  },
  {
    id: "04",
    title: "Car Shipping",
    description: "Nationwide vehicle logistics across Ghana. From Accra to Tamale, Kumasi to Cape Coast — we deliver your vehicle safely and on schedule.",
    whatsappMessage: "Hi F1 Deals, I need to ship a vehicle. Can you provide a quote?",
  },
  {
    id: "05",
    title: "Maintenance & Repairs",
    description: "Keep your vehicle in peak condition with our network of trusted mechanics and service centers. From routine maintenance to complex repairs.",
    whatsappMessage: "Hi F1 Deals, I need maintenance/repair service for my car. Can you help?",
  },
  {
    id: "06",
    title: "Parts & Accessories",
    description: "Genuine and aftermarket parts sourced for any make and model. We locate hard-to-find components and deliver them to your doorstep or preferred mechanic.",
    whatsappMessage: "Hi F1 Deals, I'm looking for car parts. Can you help me source what I need?",
  },
];

export function getWhatsAppLink(message) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}