const logger = require('../utils/logger');
const { connection } = require('../config/queues');
const prisma = require('../config/prisma');
const { Worker } = require('bullmq');

const emailWorker = new Worker('emailQueue', async (job) => {
  if (job.name === 'send-enquiry-email') {
    const { enquiryId, name, phoneNumber, email, message, type, carName } = job.data;

    const adminEmail = process.env.ADMIN_EMAIL || 'ingawintiti@gmail.com';
    const senderEmail = process.env.SENDER_EMAIL || 'ingawintiti@gmail.com';
    const senderName = process.env.SENDER_NAME || 'F1 Deals';
    const brevoApiKey = process.env.BREVO_API_KEY;

    const typeLabels = {
      Financing: '💰 Financing Enquiry',
      TradeIn: '🔄 Trade-In Enquiry',
      General: '📬 General Enquiry',
    };

    const typeLabel = typeLabels[type] || 'New Enquiry';
    const carSection = carName
      ? `<tr><td style="padding:8px 0;color:#6b7280;font-size:13px;width:130px">Vehicle</td><td style="padding:8px 0;font-weight:600;color:#111827;font-size:13px">${carName}</td></tr>`
      : '';

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:'Helvetica Neue',Arial,sans-serif">
  <table cellpadding="0" cellspacing="0" width="100%" style="background:#f9fafb;padding:40px 0">
    <tr>
      <td align="center">
        <table cellpadding="0" cellspacing="0" width="560" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
          <!-- Header -->
          <tr>
            <td style="background:#dc2626;padding:28px 32px">
              <p style="margin:0;color:#ffffff;font-size:11px;letter-spacing:3px;text-transform:uppercase;font-weight:600">F1 DEALS ADMIN</p>
              <h1 style="margin:8px 0 0;color:#ffffff;font-size:22px;font-weight:700">${typeLabel}</h1>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px">
              <p style="margin:0 0 24px;color:#374151;font-size:14px;line-height:1.6">
                A new enquiry has just been submitted on your website. Here are the details:
              </p>
              <table cellpadding="0" cellspacing="0" width="100%" style="border-top:1px solid #e5e7eb">
                <tr>
                  <td style="padding:8px 0;color:#6b7280;font-size:13px;width:130px">Name</td>
                  <td style="padding:8px 0;font-weight:600;color:#111827;font-size:13px">${name}</td>
                </tr>
                <tr style="border-top:1px solid #f3f4f6">
                  <td style="padding:8px 0;color:#6b7280;font-size:13px">Phone</td>
                  <td style="padding:8px 0;font-weight:600;color:#111827;font-size:13px">${phoneNumber}</td>
                </tr>
                ${email ? `<tr style="border-top:1px solid #f3f4f6"><td style="padding:8px 0;color:#6b7280;font-size:13px">Email</td><td style="padding:8px 0;font-weight:600;color:#111827;font-size:13px">${email}</td></tr>` : ''}
                ${carSection ? `<tr style="border-top:1px solid #f3f4f6">${carSection}</tr>` : ''}
                <tr style="border-top:1px solid #f3f4f6">
                  <td style="padding:8px 0;color:#6b7280;font-size:13px;vertical-align:top">Enquiry Type</td>
                  <td style="padding:8px 0;font-size:13px">
                    <span style="background:#fef2f2;color:#dc2626;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:600">${type}</span>
                  </td>
                </tr>
              </table>
              <!-- Message Box -->
              <div style="background:#f9fafb;border-left:3px solid #dc2626;padding:16px;margin:24px 0;border-radius:0 4px 4px 0">
                <p style="margin:0 0 4px;font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#9ca3af;font-weight:600">Message</p>
                <p style="margin:0;color:#374151;font-size:14px;line-height:1.7;white-space:pre-wrap">${message}</p>
              </div>
              <!-- CTA -->
              <p style="margin:24px 0 0;color:#6b7280;font-size:12px">
                Reply to this email or contact the customer directly at <strong>${phoneNumber}</strong> to follow up.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#f9fafb;padding:16px 32px;border-top:1px solid #e5e7eb">
              <p style="margin:0;color:#9ca3af;font-size:11px">
                This email was automatically generated by F1 Deals. &copy; ${new Date().getFullYear()} F1 Deals.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

    const payload = {
      sender: { name: senderName, email: senderEmail },
      to: [{ email: adminEmail }],
      subject: `[F1 Deals] ${typeLabel} from ${name}`,
      htmlContent: html,
      textContent: `New ${type} enquiry from ${name}\nPhone: ${phoneNumber}\nEmail: ${email || 'N/A'}${carName ? `\nVehicle: ${carName}` : ''}\n\n${message}`
    };

    if (email) {
      payload.replyTo = { email };
    }

    const response = await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'api-key': brevoApiKey
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorData = await response.text();
      throw new Error(`Brevo API Error: ${response.status} ${errorData}`);
    }

    await prisma.enquiry.update({
      where: { id: enquiryId },
      data: { emailSentAt: new Date() }
    });

    logger.info({ enquiryId }, 'Enquiry email delivered successfully');
  }
}, { connection });

emailWorker.on('failed', (job, err) => {
  logger.error({ jobId: job?.id, err }, 'Email job failed');
});

emailWorker.on('completed', (job) => {
  logger.info({ jobId: job.id }, 'Email job completed');
});

module.exports = emailWorker;
